version: '3'

services:
  backend:
    x-develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
    build: ./backend
    # volumes:
    #   - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  
  frontend:
    x-develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    build: ./frontend
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
